"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 경로
ENV_FILE = BASE_DIR / ".env"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!p^7tx3=3_6xru-fe^5*m3_zg7sv48@8d0p4rmxg)4#%%=3m0!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "corsheaders",

    # Django REST Framework
    "rest_framework",

    # API 테스트 앱
    "api",

    "patterns",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

def get_env_value(key):
    """
    .env 파일에서 지정한 환경변수 값을 읽습니다.

    예:
        MYSQL_PASSWORD=1234

    get_env_value("MYSQL_PASSWORD")
    → "1234"
    """
    if not ENV_FILE.exists():
        return os.getenv(key)

    with open(ENV_FILE, "r", encoding="utf-8") as env_file:
        for line in env_file:
            line = line.strip()

            # 빈 줄이나 주석은 무시합니다.
            if not line or line.startswith("#"):
                continue

            # KEY=VALUE 형태로 분리합니다.
            if "=" not in line:
                continue

            env_key, env_value = line.split("=", 1)

            if env_key.strip() == key:
                return env_value.strip()

    return os.getenv(key)

# ---------------------------------------------------------
# Database
# ---------------------------------------------------------
# 기존 SQLite 대신 MySQL을 사용합니다.
#
# Django
#   ↓
# mysqlclient
#   ↓
# MySQL Server
#   ↓
# dot_pattern_db
# ---------------------------------------------------------

DATABASES = {
    "default": {
        # MySQL 데이터베이스 엔진을 사용합니다.
        "ENGINE": "django.db.backends.mysql",

        # 우리가 MySQL에서 생성한 데이터베이스 이름입니다.
        "NAME": get_env_value("MYSQL_DATABASE"),

        # MySQL 서버 주소입니다.
        # 현재는 같은 컴퓨터에서 실행하므로 localhost를 사용합니다.
        "HOST": get_env_value("MYSQL_HOST"),

        # MySQL 기본 포트입니다.
        "PORT": get_env_value("MYSQL_PORT"),

        # MySQL root 계정입니다.
        "USER": get_env_value("MYSQL_USER"),

        # MySQL 설치/configurator에서 설정한 root 비밀번호입니다.
        "PASSWORD": get_env_value("MYSQL_PASSWORD"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Django REST Framework 설정
REST_FRAMEWORK = {
    # 기본 인증 방식으로 JWT를 사용합니다.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# ======================================================
# CORS 설정
# ======================================================
# React 개발 서버에서 Django API에 요청할 수 있도록 허용합니다.
#
# React : http://127.0.0.1:5173
# Django: http://127.0.0.1:8001
#
# 개발 환경에서만 사용하는 설정입니다.
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]